sweep:
  - num_request_repeats: [1]
    max_num_seqs: [8, 16, 32, 64, 128, 256]
  - num_request_repeats: [2]
    max_num_seqs: [512]
  - num_request_repeats: [4]
    max_num_seqs: [1024]
  - num_request_repeats: [5]
    max_num_seqs: [2048]
  - numm_gpus: [8]
    num_request_repeats: [8]
    max_num_seqs: [3072]
  - numm_gpus: [8]
    num_request_repeats: [10]
    max_num_seqs: [4096]
