sweep:
  - num_request_repeats: [1]
    max_num_seqs: [8, 16, 32, 64, 96, 128]
  - num_request_repeats: [2]
    max_num_seqs: [192, 256]
  - num_gpus: [2]
    num_request_repeats: [3]
    max_num_seqs: [384]
  - num_gpus: [2]
    num_request_repeats: [4]
    max_num_seqs: [512]
  - num_gpus: [2]
    num_request_repeats: [5]
    max_num_seqs: [768]
  - num_gpus: [2]
    num_request_repeats: [6]
    max_num_seqs: [1024]
  - num_gpus: [2]
    num_request_repeats: [9]
    max_num_seqs: [1536]
  - num_gpus: [2]
    num_request_repeats: [12]
    max_num_seqs: [2048]
