[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlenergy"
version = "3.0.0"
description = "The ML.ENERGY Benchmark"
readme = "README.md"
authors = [
    {name = "The ML.ENERGY Initiative"},
]
license = "Apache-2.0"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.14",
    "datasets>=4.0.0",
    "pillow>=11.3.0",
    "pydantic>=2.11.7",
    "transformers>=4.53.2",
    "tyro>=0.9.26",
    "zeus>=0.12.0",
]

[tool.setuptools.packages.find]
where = ["mlenergy"]

[dependency-groups]
dev = [
    "pyright>=1.1.403",
    "ruff>=0.12.4",
]
