sweep:
  - num_request_repeats: [1]
    max_num_seqs: [8, 16, 32, 64, 128, 256]
  - num_request_repeats: [2]
    max_num_seqs: [512, 1024]
  - num_request_repeats: [3]
    max_num_seqs: [2048]
  - num_gpus: [8]
    num_request_repeats: [6]
    max_num_seqs: [4096]
