async-scheduling: true
max-num-batched-tokens: 8192
max-model-len: 20480
dtype: bfloat16
trust-remote-code: true
tokenizer-mode: mistral
config-format: mistral
load-format: mistral
api-server-count: 3
