sweep:
  - num_request_repeats: [1]
    max_num_seqs: [8, 16, 32, 64]
  - num_request_repeats: [2]
    max_num_seqs: [96, 128, 192, 256]
  - num_request_repeats: [3]
    max_num_seqs: [384, 512]
  - num_request_repeats: [5]
    max_num_seqs: [768]
  - num_request_repeats: [6]
    max_num_seqs: [1024]
  - num_request_repeats: [9]
    max_num_seqs: [1536]
  - num_request_repeats: [12]
    max_num_seqs: [2048]
