command_template: |
  python -m mlenergy.llm.benchmark \
    --container-runtime {container_runtime} \
    --server-image {server_image} \
    --max-output-tokens {max_output_tokens} \
    workload:audio-chat \
    --workload.base-dir run/mllm \
    --workload.model-id {model_id} \
    --workload.num-requests {num_requests} \
    --workload.num-audios {num_audios} \
    --workload.audio-data-dir ${{AUDIO_DATA_DIR:?AUDIO_DATA_DIR not set}} \
    --workload.gpu-model {gpu_model} \
    --workload.num-gpus {num_gpus} \
    --workload.max-num-seqs {max_num_seqs}

workload_defaults:
  max_output_tokens: 4096
  num_requests: 1024
  num_audios: 1

sweep_defaults:
  - max_num_seqs: [8, 16, 32, 64, 96, 128, 192, 256, 384, 512]
