command_template: |
  python -m mlenergy.llm.benchmark \
    --container-runtime {container_runtime} \
    --server-image {server_image} \
    --max-output-tokens 4096 \
    workload:audio-chat \
    --workload.base-dir run/mllm \
    --workload.model-id {model_id} \
    --workload.num-requests 1024 \
    --workload.num-audios 1 \
    --workload.audio-data-dir ${{AUDIO_DATA_DIR:?AUDIO_DATA_DIR not set}} \
    --workload.gpu-model {gpu_model} \
    --workload.max-num-seqs {max_num_seqs}

sweep_defaults:
  - max_num_seqs: [8, 16, 32, 64, 96, 128, 192, 256, 384, 512]
