sweep:
  - num_request_repeats: [1]
    max_num_seqs: [8, 16, 32, 64, 128]
  - num_request_repeats: [2]
    max_num_seqs: [256]
  - num_gpus: [8]
    num_request_repeats: [3]
    max_num_seqs: [384, 512]
  - num_gpus: [8]
    num_request_repeats: [5]
    max_num_seqs: [768]
