sweep:
  - num_request_repeats: [1]
    max_num_seqs: [8, 16, 32, 64, 128]
  - num_request_repeats: [2]
    max_num_seqs: [256, 512]
  - num_request_repeats: [4]
    max_num_seqs: [1024]
  - num_request_repeats: [6]
    max_num_seqs: [2048]
