command_template: |
  python -m mlenergy.llm.benchmark \
    --container-runtime {container_runtime} \
    --server-image {server_image} \
    --max-output-tokens 15360 \
    workload:gpqa \
    --workload.base-dir run/llm/gpqa/{model_id}/{gpu_model} \
    --workload.model-id {model_id} \
    --workload.num-requests 198 \
    --workload.gpu-model {gpu_model} \
    --workload.max-num-seqs {max_num_seqs}

sweep_defaults:
  - max_num_seqs: [8, 16, 32, 64, 96, 128, 192, 256, 384, 512]
