command_template: |
  python -m mlenergy.llm.benchmark \
    --container-runtime {container_runtime} \
    --server-image {server_image} \
    --max-output-tokens {max_output_tokens} \
    workload:gpqa \
    --workload.base-dir {run_dir}/llm \
    --workload.model-id {model_id} \
    --workload.num-requests {num_requests} \
    --workload.gpu-model {gpu_model} \
    --workload.num-gpus {num_gpus} \
    --workload.max-num-seqs {max_num_seqs}

workload_defaults:
  max_output_tokens: 32768
  run_dir: run

sweep_defaults:
  - num_requests: [198]
    max_num_seqs: [8, 16, 32, 64, 96, 128]
  - num_requests: [396]
    max_num_seqs: [192, 256]
  - num_requests: [594]
    max_num_seqs: [384, 512]
