sweep:
  - num_gpus: [4]
    num_request_repeats: [1]
    max_num_seqs: [8, 16, 32, 64, 96]
  - num_gpus: [8]
    num_request_repeats: [1]
    max_num_seqs: [8, 16, 32, 64, 96, 128]
  - num_gpus: [8]
    num_request_repeats: [2]
    max_num_seqs: [192, 256]
